image: maxistar/android:latest

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - build
  - execute

build:
  stage: build
  tags:
    - fomalgaut

  script:
    - echo "Building"
    - cp local.properties.dist local.properties
    - gradle assembleDebug
    - gradle compileDebugSources
    - gradle compileDebugAndroidTestSources
    - gradle assembleAndroidTest
    - echo "Upload compiled binaries"
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk pi@altair-int.maxistar.ru:/home/pi/tests/texteditor/app-debug-androidTest.apk
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null app/build/outputs/apk/debug/app-debug.apk pi@altair-int.maxistar.ru:/home/pi/tests/texteditor/app-debug.apk
    - echo "Done stage Fomalgaut"

execute:
  stage: execute
  tags:
    - altair
  script:
    - echo "Execute Compliled Tests"
    - adb -s ZY223NB8FP uninstall com.maxistar.textpad.test
    - adb -s ZY223NB8FP uninstall com.maxistar.textpad
    - adb -s ZY223NB8FP install -r -t /home/pi/tests/texteditor/app-debug-androidTest.apk
    - adb -s ZY223NB8FP install -r -t /home/pi/tests/texteditor/app-debug.apk
    - echo "Run tests"
    - adb -s ZY223NB8FP shell am instrument -w -e debug false com.maxistar.textpad.test/androidx.test.runner.AndroidJUnitRunner

