image: maxistar/android:latest

stages:
  - build

build:
  stage: build
  tags:
    - docker

  script:
    - echo "Building"
    - cp local.properties.dist local.properties
    - gradle assembleDebug
    - gradle compileDebugSources
    - gradle compileDebugAndroidTestSources
    - gradle assembleAndroidTest

